# Generated by Django 6.0.1 on 2026-01-15 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен пользователя',
                'verbose_name_plural': 'Токены пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='blog_userto_token_06eaf8_idx'), models.Index(fields=['user', 'is_active'], name='blog_userto_user_id_161269_idx')],
            },
        ),
    ]
